
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.6.12"
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

# RPC Configuration
[rpc_endpoints]
arbitrum = "https://arbitrum-mainnet.infura.io/v3/8954371f2e184c749aebb54f6b0b5d33"
avalanche = "https://avalanche-mainnet.infura.io/v3/8954371f2e184c749aebb54f6b0b5d33"

# Etherscan Configuration
[etherscan]
arbitrum = { key = "YACJR46WQHQXVWE3TN5X285MXMTHFJC326", chain = 42161 }

# Profile for fork testing
[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
